export const cardsData = [
    {
        id: 1,
        name: 'Full-stack Food Recognition App',
        subName: 'A smart full-stack web application based on Clarifais artificial intelligence API created with React.js, Node.js and Express.',
        subtitle: 'UI Design | Frontend | Backend | PostgreSQL',
        mainCopy:'This smart food-recogition App makes use of a food recognition API and detects the ingredients in any image supplied, showcasing food. It is a handy app for food bloggers to get tag suggestions for images, with just one click.',
        image: "../images/food-recognition-hero.png",
        live: "https://food-recognition-smart-app.herokuapp.com",
        code: "https://github.com/AntoniaT/food-recognition-app",
        team: "Name, Name, Name",
        role: "React.js, Node, Express.js, Nodemon, PostgreSQL",
        duration: "4 weeks",
        deliverables: "Front-end with React.js, UI Design, Back-end sign in and registering with postgreSQL database, clarifai API",
        problem: "Develop both the front-end and back-end for a simple web application that uses an artificial intelligence API. This is a project I made while participating in a Udemy course that teaches Full-stack development. Since I had so much fun building this app, I wanted to make it look nice too.",
        leftTitle: 'The Back-end',
        leftImg: '../images/food-recognition-app-screen2.png',
        leftCopy: 'I used Node, Express.js and PostgreSQL in order to create this web App. The focus was on creating my own server and database and being able to connect everything with the front-end, which is built with React.js. This is my first full-stack app and it is a project which I used for learning, rather than creating the most innovative application. It comes with just one feature so far which I might expand, because I had a lot of fun making it.',
        rightTitle: 'The User Interface',
        rightImg: '../images/food-recognition-app-screens.png',
        rightCopy: 'Once a user has logged in or registered for the platform, the user interface of the home screen displays the users name and his rank. On the home screen, the user can upload an image and click the detect button to get tag suggestions for this image. The rank is an indicator for how many images the user already has uploaded and detected. On the bottom of the page is a simple navigation.',
        leftSecTitle: '',
        leftSecImg: '',
        leftSecCopy: '',
        rightSecTitle: '',
        rightSecImg: '',
        rightSecCopy: '',        
        leftThirdTitle: '',
        leftThirdImg: '',
        leftThirdCopy: '',
        rightThirdTitle: '',
        rightThirdImg: '',
        rightThirdCopy: '',
        tags: 'smart react js design app api clarifai frontend front-end full-stack full stack node.js node bycrypt database backend postgresql'
    },
    {
        id: 2,
        name: 'Website Design & Development for a Surgeon',
        subName: 'A fully-designed website, coded with HTML5, Sass and vanilla JS',
        subtitle: 'Branding | Web Design | Web Development',
        mainCopy:'Dr. Stefan Uranitsch, a visceral surgeon opened up his practice in Graz, Austria and needed a modern website to promote his services to prospective patients. He imagined his website to have a fresh and modern look, but he also wanted to communicate the friendly atmosphere of his practice and his personality.',
        image: "../images/mockup-doctor1.png",
        live: "https://dr-uranitsch.at",
        code: "https://github.com/AntoniaT/doctorPage",
        team: "Name, Name, Name",
        role: "Illustrator, InDesign, XD, HTML5, CSS3, Sass, Javascript",
        duration: "8 weeks",
        deliverables: "Business Cards, Letter Template, Website Wireframes, Hi-fi Prototype, Responsive Website",
        problem: "Creating a visual identity and an online presence for a surgeon in Austria.",
        leftTitle: 'Desktop Version',
        leftImg: '../images/website-stefan-1.png',
        leftCopy: 'The desktop version of the website offers a view into the warm, nicely decorated waiting room of the practice. User tests showed, that a traditional navigation and a simplified information architecture of the site was key for usability to the target audience. The client was very pleased with the choice of the hero image, since the emphasis lied on an inviting his patients to an environment where one can feel good and taken care of.',
        rightTitle: 'Colours and Typography',
        rightImg: '../images/2.png',
        rightCopy: 'The colours should combine the traditional colour scheme associated with the profession of a surgeon, as well as to communicate trust and competence. We went with a turquoise and a desaturated dark green as primary colours, and a light grey for the backgrounds. In order to pick up the style of the Logo which already existed, I used the same font for headings and combined it with a lighter, condensed font for the navigation and body of the text.',
        leftSecTitle: 'Wireframes',
        leftSecImg: '../images/website-stefan-wireframes.png',
        leftSecCopy: 'To lay out the website and its information architecture, I started out creating wireframes for both the mobile and desktop versions of the website. It is part of the iterative process, that wireframes and prototypes undergo several changes throughout the design process. This both in regards to potential users and their feedback after testing, as well as to the clients feedback and his preferences.',
        rightSecTitle: 'Mobile Version',
        rightSecImg: '../images/4.png',
        rightSecCopy: 'In order to develop a fully responsive website, I usually start with mobile first. Here you can see some excerpts of the mobile version and the navigation of the website. This is a crucial step in UX Design, where the mobile version has to live up to the desktop website.',        
        leftThirdTitle: 'Landing Page and Subpage',
        leftThirdImg: '../images/website-stefan-2.png',
        leftThirdCopy: 'Since the website should have very basic features, mostly text and contact information, I decided to code it in plain HTML, CSS/Sass and vanilla Javascript. For the client was important that I would maintain the website in the future myself, so we agreed that using a CMS like Wordpress in the backend did not make any sense in this particular case. You can see that the design is fairly simple and clean, which communicates trust and competence to its target audience. We relied on beautiful professional imagery, to set some highlights and make the website more interesting and welcoming to his prospective patients.',
        rightThirdTitle: '',
        rightThirdImg: '',
        rightThirdCopy: '',
        tags: 'graphic design ux logo website js javascript html css'
    
    },
    {
        id: 3,
        name: 'Web & App Design Mixeat',
        subName: 'An app design and hi-fi functional prototype with a coded Campaign Website',
        subtitle: 'User Interface Design | UX | Concept Development | HTML Campaign Website',
        mainCopy:'A personal chef right in your pocket: drag and drop your food into your personal fridge, shake it - a meal will be generated based on what you have at home. Our app does not only feed hungry people, we also aim to reduce food waste in private households!',
        image: "../images/app-design.png",
        live: "http://anckdesign.com/01-web/app",
        code: "",
        team: "Name, Name, Name",
        role: "Illustrator, UI Design, HTML5, CSS3",
        duration: "4 weeks",
        deliverables: "Problem formulation, competitor analysis, Personas, Wireframes, Hi-fi Prototype, Campaign Website in HTML and CSS",
        problem: "This was a first-semester group project at KEA, my university. We had to come up with an innovative app and develop it step-by-step. With this project we developed an understanding for the iterative design process and user centered design thinking. The problem we were trying to solve, was the following: People living on a budget often fall short on ideas of what to cook after a long day at work or school. They end up eating fast food and wasting the food in their fridge. MIXEAT solves that problem!",
        leftTitle: 'Personas',
        leftImg: '../images/Persona1.png',
        leftCopy: 'In working with personas, we ended up with two types of characters. Where one is an extrovert and eager to engage in social happenings, the other is an introvert, mainly purchasing the application in order to create recipes and find online deals. Despite the difference between the two, our personas represent our major target audience of young adults. Personalities, backgrounds, goals and values are based on both qualitative and quantitative research we conducted on young people in Copenhagen.',
        rightTitle: 'Wireframes',
        rightImg: '../images/wireframes-mixeat.png',
        rightCopy: 'We started our process with defining mission, vision and values of our business. Once we laid out the scope of our service app, we started out with static paper wireframes. With the wireframe we created the structure of our entire project layout, making it easier to later build on individual parts. First user testing and user flows were conducted on the early wireframes and paper prototypes, in order to narrow down key layouts and investigate interaction patterns.',
        leftSecTitle: 'Design Mockups',
        leftSecImg: '../images/prototype-mixeat.png',
        leftSecCopy: 'After discussing various design ideas, we created a mid fidelity mockup to reflect on the design choices and the overall atmosphere of our app.',
        rightSecTitle: 'Hi-fi Prototype',
        rightSecImg: '../images/prototypes.png',
        rightSecCopy: 'After testing both our Mockup and our paper prototype with real users, we created a hi-fi prototype in XD. This clickable prototype should be part of our pitch for potential investors. We utilized UX methods such as Think aloud testing, BERT test and 5 seconds test to validate our design choices.',        
        leftThirdTitle: 'Landing Page for Desktop',
        leftThirdImg: '../images/mixeat-laptop.png',
        leftThirdCopy: 'Finally, we developed a promotional Landing Page with a short video to advertise our App with its core features and purpose. Since this was an early HTML and CSS project, the code and design of this site was fairly simple. The project concluded with a 10 minutes pitch of our idea and digital solution.',
        rightThirdTitle: 'Something',
        rightThirdImg: 'Something',
        rightThirdCopy: 'Something',
        tags: 'web ux design coding html css'
    },
    /*{
        id: 2,
        name: 'Branding & Design Projects',
        subName: '',
        subtitle: 'Branding | Packaging | Webdesign',
        mainCopy:'The Bagel Hub is a brand design I developed for a new bagel store concept based in a vibrant and modern, yet relaxed city. I wanted to create a brand that felt fresh and delightful but also a bit cheeky. Overall, the identity is designed to express healthy and delicious food as well as a fun and relaxed atmosphere for its young target group. I also expanded the new brand and slowly created all of the print + packaging!',
        image: './images/BagelHubLogoVersion.png',
        live: "",
        code: "",
        team: "Solo project",
        role: "Illustrator, Photoshop, XD",
        duration: "6-12 weeks",
        deliverables: "Logo, packaging, website design",
        problem: "Young people living in a city need a budget friendly and healthy place to go to when exploring the city. They are millenials with a focus on a healthy lifestyle, but they usually don't want to wait for their food.",
        leftTitle: 'Personas',
        leftImg: '../images/wireframes-mixeat.png',
        leftCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        rightTitle: 'Research',
        rightImg: '../images/wireframes-mixeat.png',
        rightCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        leftSecTitle: 'Personas',
        leftSecImg: '../images/PersonasMixeat.png',
        leftSecCopy: 'In working with personas, we ended up with two types of characters. Where one is an extrovert and eager to engage in social happenings, the other is an introvert, mainly purchasing the application in order to create recipes and find online deals. Despite the difference between the two, our personas represent our major target audience of young adults. Personalities, backgrounds, goals and values are based on both qualitative and quantitative research we conducted on young people in Copenhagen.',
        rightSecTitle: 'Wireframes',
        rightSecImg: '../images/wireframes-mixeat.png',
        rightSecCopy: 'We started our process with defining mission, vision and values of our business. Once we laid out the scope of our service app, we started out with static paper wireframes. With the wireframe we created the structure of our entire project layout, making it easier to later build on individual parts. First user testing and user flows were conducted on the early wireframes and paper prototypes, in order to narrow down key layouts and investigate interaction patterns.',                
        tags: 'branding design logo graphic webdesign'

    },*/
    {
        id: 4,
        name: 'Web Design & Development for Rossana Caldarera',
        subName: 'a full-fledged online performance for a contemporary dancer using vanilla JS, Wordpress in the backend and REST API',
        subtitle: 'Concept Development | Branding | Logo Design | Website Design | Web Development',
        mainCopy:'Rossana Caldarera is a professional contemporary dancer, currently living in Italy. After years of working for a prominent dance company in Amsterdam, she is now freelancing for performing projects and teaching jobs. As her previous dance company had their own marketing department, she never had to worry about promoting her work or creating online content. Now she struggles to reach out to her target audiences and create an online presence.',
        image: '../images/exam-dancer-project-02.png',
        live: "http://anckdesign.com/kea/rossana-caldarera/",
        code: "https://github.com/AntoniaT/rossanacaldarera",
        team: "Name, Name, Name",
        role: "Adobe Illustrator and XD, HTML5, CSS3, Javascript, REST API, Wordpress, 5sec Test, BERT test",
        duration: "4 weeks",
        deliverables: "Problem formulation, competitor analysis, Personas, Customer Journey, Marketing Solution, User Testing, Wireframes, Hi-fi Prototype, Wordpress Backend System, CMS Manual",
        problem: "This was my second semester exam project for KEA, which we worked on as a group of three students. Our main research question was: How do we market Rossana as an international dance teacher, in such a way it suits her values and unique identity?",
        leftTitle: 'Moodboard',
        leftImg: '../images/moodboard-rossana.png',
        leftCopy: 'Contemporary dance is all about the combination of organic movements, beautiful lines and body strength. You should feel the energy and passion for dance from the expressive photos. At the same time you’ll also see the hours of hard work and dedication it takes to have a couple of moments in the spotlight. Since Rossana indicated she prefers earthy colours in the Design Brief, we tried to find a colour scheme that gives you a friendly and energetic feeling (warm yellow tones) but also generates trust in her capabilities as a teacher (cool blue/grey tones). The choice for earthy colours also represents her natural/down-to-earth personality, and should portray that Rossana is not a commercial dancer who just wants to become famous.',
        rightTitle: 'Personas',
        rightImg: '../images/personas-rossana.png',
        rightCopy: 'We summarized our quantitative and qualitative research on the target group in these two Personas. It was a good starting point to validate our assumptions and to repeatedly get back to during the further design process. Rossanas users will both be prospective students for her classes, as well as recruiter for bigger dance companies, theatres or other corporations looking for professional contemporary dancer.',
        leftSecTitle: 'Customer Journey',
        leftSecImg: '../images/Customer-journey-rossana4.png',
        leftSecCopy: 'The communication environment of Rossanas target group can typically range from private settings at home, on the couch, to being outside while travelling with public transport or sitting together with friends. As the target audience uses Instagram to discover dancers they like, they will be occupied with similar teachers or dance idols on the platform. With laying out the customer journey we took another step closer to making her profile even more visible and relevant for her target audience. We were aiming to gain more followers for her and setting her apart from other dancers online.',
        rightSecTitle: 'Mock-ups of Instagram posts',
        rightSecImg: '../images/Instagram-feed-mockup-1.png',
        rightSecCopy: 'Research on our target groups interests, habits and needs helped us in creating specific content for Rossanas SoMe channels. Since Rossana’s Instagram will be targeted at young dancers, we wanted to create a younger fresher vibe with color graded pictures, while still staying coherent to the website design. The pictures show more of her experience as an inspiring professional performing artist, that should make the target audience more curious about who she is and if they can follow her classes.',                
        leftThirdTitle: 'Landing Page Desktop',
        leftThirdImg: '../images/rossana-website.png',
        leftThirdCopy: 'This is the landing page I designed for Rossana. Eventually we ended up coding a different design, which one of my team mates created. You can see the alternative design when you click on the live button at the top of this page.',
        rightThirdTitle: 'Landing Page Desktop',
        rightThirdImg: '../images/rossana-website.png',
        rightThirdCopy: '',
        tags: 'frontend design ux testing javascript marketing social media instagram html css some'

    },
    {
        id: 5,
        name: 'Javascript Playground',
        subName: 'Several small projects using vanilla JS, HTML5, CSS3, SVG animation, React.js, REST API and Restdb',
        subtitle: 'Rest API | Javascript | React | Design',
        mainCopy:'Here you can find a collection of smaller projects which helped me learn the foundations of front-end development! With every little challenge I solved I got so excited and eager to learn more and master Javascript. You can find all these projects on my Github page.',
        image: "../images/todolist.png",
        live: "https://antoniat.github.io/todolist/",
        code: "https://github.com/AntoniaT/todolist",
        team: "sole projects",
        role: "HTML5, CSS3, Javascript, REST API, restdbo, React",
        duration: "from 1 day to 1 week",
        deliverables: "Code, code, code",
        problem: "Many! I started with very simple and small coding challenges to learn Javascript and common design patterns. In order to solve the given problems, I was usually breaking them down to the smallest chunk I could solve and gradually connecting the dots. All in all coding is problem solving and I am a person who never gives up until it works. With the growth of my coding knowledge I also learnt to value DRY and clean code, which is now my main priority when solving challenges.",
        leftTitle: 'Robofriends App',
        leftImg: '../images/robofriends.png',
        leftCopy: 'Robofriends was my first react app that I coded while participating in an online coding course called Zero to Mastery on Udemy. The course aims to teach you to the level of a full-stack developer and I learnt so much with all the projects we coded together.',
        rightTitle: 'Hogwarts student list',
        rightImg: '../images/studentList.png',
        rightCopy: 'This was a project we developed at kea, which was solely focused on functionality and concluded several weeks of learning Javascript. We practised sorting, filtering, removing and hacking into elements from a list with a dynamically driven database.',
        leftSecTitle: 'Displacement Map',
        leftSecImg: '../images/displacement-map.png',
        leftSecCopy: 'We created a pseudo 3D image that listens to the mouse moving. It was another task for my studies, where we learnt to work with canvas in html.',
        rightSecTitle: 'To-do-list',
        rightSecImg: '../images/todolist.png',
        rightSecCopy: 'A small App I developed for kea as well, where I practised Form elements with a focus on UX, dynamically driven by restDB as a database in the back-end. Even though it was not a must to think about the design, this tiny project demonstrates how much I love to design and code with attention to all the little details.',
        leftThirdTitle: 'Npm documentation Tutorial',
        leftThirdImg: '../images/npmTutorial.png',
        leftThirdCopy: 'The task for this school project was to write and code a documentation site for a npm package our choice. It was important to try the package, use it, test it and make it easily understandable for other developers or users.',
        rightThirdTitle: '',
        rightThirdImg: '',
        rightThirdCopy: '',
        tags: 'animation ux javascript html css rest api database ajax js canvas'

    },
    {
        id: 6,
        name: 'Mobility over Time',
        subName: 'A dynamic infographic designed with Illustrator and animated with vanilla JS',
        subtitle: 'Infographic Design | Javascript  | Animated SVG',
        mainCopy:'This project revolved around creating a dynamic infographic in form of a timeline. The overall purpose of the timeline I created is to visualize the change of human means of transport over time and its effects on our environment. It will eventually become a part of a bigger awareness campaign advertising less emission heavy ways of transport. This timeline will be expanded with more accurate data serving its purpose.To simplify the timeline as being part of this school project I decided to show only data which was accessible and easily comparable (Inventor, date of invention and a short explanation).',
        image: "../images/timeline.png",
        live: "http://anckdesign.com/kea/timeline/",
        code: "https://github.com/AntoniaT/interactive-timeline-mobility",
        team: "Name, Name, Name",
        role: "HTML, CSS, Javascript, Adobe Illustrator, SVG animation",
        duration: "2 weeks",
        deliverables: "Sketches, Data Research, Style Tile, Wireframes and Mockup, SVG Layout Diagram, JS Call Graph, Code Documentation",
        problem: "Mobility over time shows the history of human means of transport by ten chosen examples. When a vehicle is clicked, a modal opens and displays data about this type of vehicle. Please note that the examples shown are not historically conclusive, but randomly chosen and visually simplified in favour of this being a timely limited school project.",
        leftTitle: 'Sketches and Ideas',
        leftImg: '../images/sketches-timeline.png',
        leftCopy: 'I started with sketching the architecture of my timeline and thought about how I wanted to present the data. I loved playing with different styles of illustrating the vehicles, since there were no given limitations.',
        rightTitle: 'Research',
        rightImg: '../images/wireframe-timeline.png',
        rightCopy: 'The whole landscape of the timeline is animated and horizontally scrollable, as if it was a real life scenario. Clouds are moving, birds are flying, trees are bowing its crowns. These animations are purily made in CSS, targeting the specific elements in the SVG. To indicate that each single vehicle is clickable, the opacity changes on hover and a pointer is shown once the vehicle is hovered. Additionally, to create a flow leading the user to scroll towards right and follow the timeline, all vehicles are moving constantly to the right side, towards „the future“. This animation is created in Javascript with a request animation frame method.',
        leftSecTitle: 'Style Tile',
        leftSecImg: '../images/style-tile-timeline.png',
        leftSecCopy: 'Using flat design as an overall style helps telling my story in a simple way. The vehicles are animated to create a flow for the users as they scroll through the timeline from past to present. I carefully chose a bright color palette consisting of vibrant pink, blue and green colors to envoke the feeling of entering a wonderland that sets a tone of lightness and positivity. The user should be drawn to the beauty of pure nature and calmness in the first part of the timeline. This particular mix of colors looks happy, in contrast to the grey of the future that will draw the user’s eyes to the change of the environment and its consequences.',
        rightSecTitle: 'SVG Layout Diagram',
        rightSecImg: '../images/svg-callgraph.png',
        rightSecCopy: 'Finally I documented my coding process with call graphs and diagrams. Here you can see an excerpt of a diagram on how the svg animation was planned (in pink) and a Javascript call graph (in blue).',        
        leftThirdTitle: '',
        leftThirdImg: '',
        leftThirdCopy: '',
        rightThirdTitle: '',
        rightThirdImg: '',
        rightThirdCopy: '',
        tags: 'javascript html css design infographic svg animation js illustrator'

    }
/*     {
        id: 6,
        name: 'Web App Design UX Huset CPH',
        subName: 'UI design and development with a user-centered approach',
        subtitle: 'Persona driven User Interface Design | UX | Concept Development | Wordpress backend',
        mainCopy:'A personal chef right in your pocket: drag and drop your food into your personal fridge, shake it - a meal will be generated based on what you have at home. Our app does not only feed hungry people, we also aim to reduce food waste in private households!',
        image: "../images/huset-03-03.png",
        live: "http://anckdesign.com/kea/husetArtist/index.html",
        code: "https://github.com/AntoniaT/husetWebApp",
        team: "Name, Name, Name",
        role: "HTML5, CSS3, Javascript, REST API, Wordpress, User research and testing, Adobe XD, Illustrator",
        duration: "4 weeks",
        deliverables: "Problem formulation, competitor analysis, Personas, Wireframes, Hi-fi Prototype",
        problem: "People living on a budget often encounter the problem not knowing what to cook after a long day at work or school. They end up eating fast food and wasting the food in their fridge. MIXEAT solves that problem! We generated an app where the user only puts in the stuff in his fridge via drag and drop and ends up getting three suggested dishes. If additional ingredients are needed, the app guides the user to the closest discounter or supermarket.",
        leftTitle: 'Personas',
        leftImg: '../images/persona-artist-huset.png',
        leftCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        rightTitle: 'Research',
        rightImg: '../images/web_app_structure.png',
        rightCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        leftSecTitle: 'Puzzle Game',
        leftSecImg: '../images/displacement-map.png',
        leftSecCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        rightSecTitle: 'Interactive Timeline',
        rightSecImg: '../images/timeline.png',
        rightSecCopy: 'This was a small App I developed for school, where we practised Form elements with a focus on UX, dynamically driven by restDB as a database in the back-end.',        
        leftThirdTitle: '',
        leftThirdImg: '',
        leftThirdCopy: '',
        rightThirdTitle: '',
        rightThirdImg: '',
        rightThirdCopy: '',
        tags: 'frontend design ux xd prototype wordpress backend javascript user-centered rest api'

    }, 
    {
        id: 7,
        name: 'Interactive Animation Crazy Stupid Love',
        subName: 'A fun JS powered interactive animation based on a popular movie, planned, illustrated and coded',
        subtitle: 'Animation | Javascript | Storytelling | Content Development',
        mainCopy:'Create an interactive production on a movie scene with a given theme. This was by far the funniest project for me! Of course due to time restraints, we had to give up on a few more fun ideas or stuff we created.',
        image: "../images/crazystupid.png",
        live: "",
        code: "",
        team: "Name, Name, Name",
        role: "UX Designer",
        duration: "2 weeks",
        deliverables: "Concept Development, Content Creation, Storyboard, Sequence Diagram, User Testing",
        problem: "People living on a budget often encounter the problem not knowing what to cook after a long day at work or school. They end up eating fast food and wasting the food in their fridge. MIXEAT solves that problem! We generated an app where the user only puts in the stuff in his fridge via drag and drop and ends up getting three suggested dishes. If additional ingredients are needed, the app guides the user to the closest discounter or supermarket.",
        leftTitle: 'Personas Collage',
        leftImg: '../images/personascollage.png',
        leftCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        rightTitle: 'Sketches',
        rightImg: '../images/Sequence-diagram.png',
        rightCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        leftSecTitle: 'Storyboard',
        leftSecImg: '../images/storyboard-crazystupid.png',
        leftSecCopy: 'The desktop version of the website offers a big landing picture of the product, followed by a simple and easy-to-use homepage. The main purpose is showcasing the menu as well as the overall fresh feel of the Bagel Store. ',
        rightSecTitle: 'Sequence Diagram',
        rightSecImg: '../images/Sequence-diagram.png',
        rightSecCopy: 'This was a small App I developed for school, where we practised Form elements with a focus on UX, dynamically driven by restDB as a database in the back-end.',        
        leftThirdTitle: '',
        leftThirdImg: '',
        leftThirdCopy: '',
        rightThirdTitle: '',
        rightThirdImg: '',
        rightThirdCopy: '',
        tags: 'javascript animation frontend design ux illustrator storyboard html css'
    }*/
];